(*----
  Name: defaults.ml
  Copyright Matthew Wahab 2005-2019
  Author: Matthew Wahab <mwb.cde@gmail.com>

  This file is part of HSeq

  HSeq is free software; you can redistribute it and/or modify it under the
  terms of the Lesser GNU General Public License as published by the Free
  Software Foundation; either version 3, or (at your option) any later version.

  HSeq is distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
  A PARTICULAR PURPOSE.  See the Lesser GNU General Public License for more
  details.

  You should have received a copy of the Lesser GNU General Public
  License along with HSeq.  If not see <http://www.gnu.org/licenses/>.
  ----*)

(*
  Default values for HSeq settings.

  Uses the configuration data in module Config (config.{mli,ml}) generated by
  the toplevel configure script.
*)

let basedir = Config.value_BaseDir
let libdir = Config.value_LibDir
let thydir = Config.value_ThyDir

let version = "Feb2019"
