(*----
  Copyright (c) 2005-2021 Matthew Wahab <mwb.cde@gmail.com>

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.
----*)

(*
  Default values for HSeq settings.

  Uses the configuration data in module Config (config.{mli,ml}) generated by
  the toplevel configure script.
*)

let basedir = Config.value_BaseDir
let libdir = Config.value_LibDir
let thydir = Config.value_ThyDir

let version = "2020.07"
