#####
# Makefile for building sub-directories
#
# Set variables to be used by Makefile.sub and OMakefile.sub
# This is a template to be copied into each directory to be built.
#
# This file must be readable by both GNU Make and OMake
# (so it should only have variable settings of the form 'X = Y').
#####

####
# The variables to be set in Makefile.def
###

###
# Header, byte code and native code files
###

# FILES: The list of file names
FILES =

# HEADERS: the list of header (.cmi) files 
# HEADERS =

# MLHEADERS: the list of ML header (.mli) files 
# MLHEADERS = 

# CODE: the list of code (.cmo) files 
# CODE =

# NATCODE: the list of native code (.cmx) files 
# NATCODE = 

###
# Generated libraries
###

# LIBFILES: The list of library files built.
# If LIBFILES is defined then the library is built and installed
# If LIBFILES is empty, the code (.cmo) files are built and installed.
# LIBFILES = 

# BYTELIBS: The list of library (.cma) files built
# BYTELIBS = 

# NATLIB: The list of native code library (.cmxa) files built
# NATLIBS =

###
# Documentation
###

# DOCTYPE = -html

# DOCFILES: File from which documentation is to be built
# DOCFILES = 

# DOCDATA: File to be emitted as a link
# DOCDATA = 

# DOCPREV: File to be loaded as a link to previous documentation
# (using -load)
# DOCPREV = 

###
# Installing files
###

# INSTALL_OTHER_FILES: Additional files to install
# INSTALL_OTHER_FILES = 


###
# End of Makefile.def variables
###
