clean:
	rm -f *.data
	rm -f *.html *.css
	rm -f *.info
	rm -f *.cmi
	rm -f *.mli
	rm -f *.cmo
	rm -f *.cmx 
	rm -f *.o
	rm -f *~

libclean: clean
	rm -f *.cmi
	rm -f *.cma *.cmxa

reallyclean: clean libclean
	rm -f depend


