########################################################## --*- Makefile -*--
# Copyright (c) 2011-2021 Matthew Wahab <mwb.cde@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
######################################################################

###
# The project root
PROJ_ROOT=../..

##
# The document to build
DOCUMENTS=hseq

##
# Module settings

# The module include directories
MODULE_INCLUDE=$(PROJ_ROOT)/doc

##
# Settings for each document

# The texinfo sources
hseq_TEXINFO=hseq.texi

# Document include directory [default: $(MODULE_INCLUDE)]
#hseq_INCLUDE=

# Document output name [default: hseq]
#hseq_OUTPUT=

# Name of the output html directory
#    [default: $(hseq_output).html]
#hseq_HTMLDIR=

# Name of the output info directory [default: $(hseq_output).info]
#hseq_INFODIR=


######################################################################
# Don't edit anything below this line.
#####

# Include the standard template.
include $(PROJ_ROOT)/doc/Makefile.docrules
