@c Copyright (c) 2021 Matthew Wahab <mwb.cde@gmail.com>
@c
@c This Source Code Form is subject to the terms of the Mozilla Public
@c License, v. 2.0. If a copy of the MPL was not distributed with this
@c file, You can obtain one at http://mozilla.org/MPL/2.0/.

@c @setfilename tactics.info

@node Tactics and Tacticals
@chapter Tactics and Tacticals

@menu
* Tactic Name:: Tactic Name.
@end menu





